export interface CountryCode {
  code: string;
  dial: string;
  flag: string;
  name: string;
}

const EN_NAMES: Record<string, string> = {
  OM: 'Oman', SA: 'Saudi Arabia', AE: 'UAE', KW: 'Kuwait', BH: 'Bahrain', QA: 'Qatar',
  IQ: 'Iraq', EG: 'Egypt', JO: 'Jordan', LB: 'Lebanon', SY: 'Syria', PS: 'Palestine',
  YE: 'Yemen', LY: 'Libya', TN: 'Tunisia', DZ: 'Algeria', MA: 'Morocco', SD: 'Sudan',
  SO: 'Somalia', MR: 'Mauritania', DJ: 'Djibouti', KM: 'Comoros',
  TR: 'Turkey', IR: 'Iran', PK: 'Pakistan', IN: 'India', BD: 'Bangladesh',
  ID: 'Indonesia', MY: 'Malaysia', US: 'USA', CA: 'Canada', GB: 'UK',
  DE: 'Germany', FR: 'France', IT: 'Italy', ES: 'Spain', NL: 'Netherlands',
  BE: 'Belgium', SE: 'Sweden', NO: 'Norway', DK: 'Denmark', CH: 'Switzerland',
  AT: 'Austria', AU: 'Australia', NZ: 'New Zealand', JP: 'Japan', KR: 'South Korea',
  CN: 'China', SG: 'Singapore', TH: 'Thailand', PH: 'Philippines', ZA: 'South Africa',
  NG: 'Nigeria', KE: 'Kenya', GH: 'Ghana', BR: 'Brazil', MX: 'Mexico',
  AR: 'Argentina', CL: 'Chile', CO: 'Colombia', RU: 'Russia', UA: 'Ukraine',
  PL: 'Poland', CZ: 'Czechia', RO: 'Romania', GR: 'Greece', PT: 'Portugal',
  IE: 'Ireland', FI: 'Finland', HU: 'Hungary',
};

const _countryCodes: CountryCode[] = [
  { code: 'OM', dial: '+968', flag: '🇴🇲', name: 'عُمان' },
  { code: 'SA', dial: '+966', flag: '🇸🇦', name: 'السعودية' },
  { code: 'AE', dial: '+971', flag: '🇦🇪', name: 'الإمارات' },
  { code: 'KW', dial: '+965', flag: '🇰🇼', name: 'الكويت' },
  { code: 'BH', dial: '+973', flag: '🇧🇭', name: 'البحرين' },
  { code: 'QA', dial: '+974', flag: '🇶🇦', name: 'قطر' },
  { code: 'IQ', dial: '+964', flag: '🇮🇶', name: 'العراق' },
  { code: 'EG', dial: '+20', flag: '🇪🇬', name: 'مصر' },
  { code: 'JO', dial: '+962', flag: '🇯🇴', name: 'الأردن' },
  { code: 'LB', dial: '+961', flag: '🇱🇧', name: 'لبنان' },
  { code: 'SY', dial: '+963', flag: '🇸🇾', name: 'سوريا' },
  { code: 'PS', dial: '+970', flag: '🇵🇸', name: 'فلسطين' },
  { code: 'YE', dial: '+967', flag: '🇾🇪', name: 'اليمن' },
  { code: 'LY', dial: '+218', flag: '🇱🇾', name: 'ليبيا' },
  { code: 'TN', dial: '+216', flag: '🇹🇳', name: 'تونس' },
  { code: 'DZ', dial: '+213', flag: '🇩🇿', name: 'الجزائر' },
  { code: 'MA', dial: '+212', flag: '🇲🇦', name: 'المغرب' },
  { code: 'SD', dial: '+249', flag: '🇸🇩', name: 'السودان' },
  { code: 'SO', dial: '+252', flag: '🇸🇴', name: 'الصومال' },
  { code: 'MR', dial: '+222', flag: '🇲🇷', name: 'موريتانيا' },
  { code: 'DJ', dial: '+253', flag: '🇩🇯', name: 'جيبوتي' },
  { code: 'KM', dial: '+269', flag: '🇰🇲', name: 'جزر القمر' },
  { code: 'TR', dial: '+90', flag: '🇹🇷', name: 'تركيا' },
  { code: 'IR', dial: '+98', flag: '🇮🇷', name: 'إيران' },
  { code: 'PK', dial: '+92', flag: '🇵🇰', name: 'باكستان' },
  { code: 'IN', dial: '+91', flag: '🇮🇳', name: 'الهند' },
  { code: 'BD', dial: '+880', flag: '🇧🇩', name: 'بنغلاديش' },
  { code: 'ID', dial: '+62', flag: '🇮🇩', name: 'إندونيسيا' },
  { code: 'MY', dial: '+60', flag: '🇲🇾', name: 'ماليزيا' },
  { code: 'US', dial: '+1', flag: '🇺🇸', name: 'أمريكا' },
  { code: 'CA', dial: '+1', flag: '🇨🇦', name: 'كندا' },
  { code: 'GB', dial: '+44', flag: '🇬🇧', name: 'بريطانيا' },
  { code: 'DE', dial: '+49', flag: '🇩🇪', name: 'ألمانيا' },
  { code: 'FR', dial: '+33', flag: '🇫🇷', name: 'فرنسا' },
  { code: 'IT', dial: '+39', flag: '🇮🇹', name: 'إيطاليا' },
  { code: 'ES', dial: '+34', flag: '🇪🇸', name: 'إسبانيا' },
  { code: 'NL', dial: '+31', flag: '🇳🇱', name: 'هولندا' },
  { code: 'BE', dial: '+32', flag: '🇧🇪', name: 'بلجيكا' },
  { code: 'SE', dial: '+46', flag: '🇸🇪', name: 'السويد' },
  { code: 'NO', dial: '+47', flag: '🇳🇴', name: 'النرويج' },
  { code: 'DK', dial: '+45', flag: '🇩🇰', name: 'الدنمارك' },
  { code: 'CH', dial: '+41', flag: '🇨🇭', name: 'سويسرا' },
  { code: 'AT', dial: '+43', flag: '🇦🇹', name: 'النمسا' },
  { code: 'AU', dial: '+61', flag: '🇦🇺', name: 'أستراليا' },
  { code: 'NZ', dial: '+64', flag: '🇳🇿', name: 'نيوزيلندا' },
  { code: 'JP', dial: '+81', flag: '🇯🇵', name: 'اليابان' },
  { code: 'KR', dial: '+82', flag: '🇰🇷', name: 'كوريا الجنوبية' },
  { code: 'CN', dial: '+86', flag: '🇨🇳', name: 'الصين' },
  { code: 'SG', dial: '+65', flag: '🇸🇬', name: 'سنغافورة' },
  { code: 'TH', dial: '+66', flag: '🇹🇭', name: 'تايلاند' },
  { code: 'PH', dial: '+63', flag: '🇵🇭', name: 'الفلبين' },
  { code: 'ZA', dial: '+27', flag: '🇿🇦', name: 'جنوب أفريقيا' },
  { code: 'NG', dial: '+234', flag: '🇳🇬', name: 'نيجيريا' },
  { code: 'KE', dial: '+254', flag: '🇰🇪', name: 'كينيا' },
  { code: 'GH', dial: '+233', flag: '🇬🇭', name: 'غانا' },
  { code: 'BR', dial: '+55', flag: '🇧🇷', name: 'البرازيل' },
  { code: 'MX', dial: '+52', flag: '🇲🇽', name: 'المكسيك' },
  { code: 'AR', dial: '+54', flag: '🇦🇷', name: 'الأرجنتين' },
  { code: 'CL', dial: '+56', flag: '🇨🇱', name: 'تشيلي' },
  { code: 'CO', dial: '+57', flag: '🇨🇴', name: 'كولومبيا' },
  { code: 'RU', dial: '+7', flag: '🇷🇺', name: 'روسيا' },
  { code: 'UA', dial: '+380', flag: '🇺🇦', name: 'أوكرانيا' },
  { code: 'PL', dial: '+48', flag: '🇵🇱', name: 'بولندا' },
  { code: 'CZ', dial: '+420', flag: '🇨🇿', name: 'التشيك' },
  { code: 'RO', dial: '+40', flag: '🇷🇴', name: 'رومانيا' },
  { code: 'GR', dial: '+30', flag: '🇬🇷', name: 'اليونان' },
  { code: 'PT', dial: '+351', flag: '🇵🇹', name: 'البرتغال' },
  { code: 'IE', dial: '+353', flag: '🇮🇪', name: 'أيرلندا' },
  { code: 'FI', dial: '+358', flag: '🇫🇮', name: 'فنلندا' },
  { code: 'HU', dial: '+36', flag: '🇭🇺', name: 'المجر' },
];

export const countryCodes = _countryCodes;

export function getCountryCodes(locale?: string): CountryCode[] {
  if (locale !== 'en') return _countryCodes;
  return _countryCodes.map(c => ({ ...c, name: EN_NAMES[c.code] ?? c.name }));
}
